In [21]:
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import to_categorical #ao invez de usar keras.utils np_utils

In [29]:
base = datasets.load_iris()
previsores = base.data
classe = base.target
classe

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [31]:
#É necessário transformar a classe em formato dummy pois teremos 3 neuronios na camada de saida
classe_dummy = to_categorical(classe)
classe_dummy

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [35]:
x_treino, x_teste, y_treino, y_teste = train_test_split(previsores, classe_dummy, test_size = 0.3, random_state = 0)

In [43]:
#Criaçao da estrutura da rede neural com a classe sequential (sequencia de camadas)
#Siginifca que as camadas serao incluidas uma apos a outra
modelo = Sequential()
#Primeira camada oculta, 5 neuronios, 4 neuronios de entrada
#'Dense' signifca que todos os neuronios sao conectados aos da proxima camada
#'Units' é a quantidade de neuronio a serem adicionados
#'Input_dim' é o parametro que informa a quantidade de neuronios na camada de entrada
modelo.add(Dense(units = 5, input_dim = 4))
#Segunda camada
modelo.add(Dense(units = 4))
#Terceira camada
#Funçao softmax pois há um problema de classificaçao com mais de duas classe
#É gerado uma probabilidade em cada neuronio
modelo.add(Dense(units = 3, activation = 'softmax'))

In [47]:
modelo.summary()
#Camadas e tipos | quantidade de neuronios | quantidade de hiperparametros

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_5 (Dense)                 │ (None, 5)              │            25 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 4)              │            24 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 3)              │            15 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 64 (256.00 B)

 Trainable params: 64 (256.00 B)

 Non-trainable params: 0 (0.00 B)

In [53]:
#Configurando os parameteos da rede neural (adam = algoritimo para atualizar os pesos (mais comum), loss = calculo do erro
modelo.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])
#treinamento, dividindo a base de treinamento em uma porcaopara validacao (validation_data)
#Ele ajusta os pesos de acordo com os dados de teste validando os dados com os de teste
modelo.fit(x_treino, y_treino, epochs = 1000, validation_data = (x_teste, y_teste))
#accuracy = valor com dados de treino, val_accuracy = é o mais importante pois é utilizado os dados de teste, ou seja, ele nao usou no treino
#loss = é o quanto está errando
#O mais importante é o val_accuracy, pois melhor demonstra a realidade, neste caso o modelo teve uma taxa de 97% de acerto

Epoch 1/1000
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 80ms/step - accuracy: 0.3725 - loss: 1.4406 - val_accuracy: 0.2444 - val_loss: 1.7334
Epoch 2/1000
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.3861 - loss: 1.4509 - val_accuracy: 0.2444 - val_loss: 1.6272
Epoch 3/1000
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.3840 - loss: 1.2801 - val_accuracy: 0.2444 - val_loss: 1.5270
Epoch 4/1000
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.3204 - loss: 1.3350 - val_accuracy: 0.2444 - val_loss: 1.4365
Epoch 5/1000
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.3392 - loss: 1.2168 - val_accuracy: 0.2667 - val_loss: 1.3586
Epoch 6/1000
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.4083 - loss: 1.0437 - val_accuracy: 0.3556 - val_loss: 1.2890
Epoch 7/1000
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.5328 - loss: 1.0575 - val_accuracy: 0.5556 - val_loss: 1.2237
Epoch 8/1000
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6420 - loss: 1.0247 - val_accuracy: 0.5778 - v

In [55]:
#Realizar previsoes e alterar o valor de saida para true or false para poder utilizar na matriz confusao
previsao = modelo.predict(x_teste)
previsao = (previsao > 0.5)
previsao

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step


array([[False, False,  True],
       [False,  True, False],
       [ True, False, False],
       [False, False,  True],
       [ True, False, False],
       [False, False,  True],
       [ True, False, False],
       [False,  True, False],
       [False,  True, False],
       [False,  True, False],
       [False, False,  True],
       [False,  True, False],
       [False,  True, False],
       [False,  True, False],
       [False,  True, False],
       [ True, False, False],
       [False,  True, False],
       [False,  True, False],
       [ True, False, False],
       [ True, False, False],
       [False, False,  True],
       [False,  True, False],
       [ True, False, False],
       [ True, False, False],
       [False, False,  True],
       [ True, False, False],
       [ True, False, False],
       [False,  True, False],
       [False,  True, False],
       [ True, False, False],
       [False, False,  True],
       [False,  True, False],
       [ True, False, False],
       [Fa

In [61]:
#Buscando o maior valor
y_teste_matrix = [np.argmax (t) for t in y_teste]
y_previsao_matrix = [np.argmax (t) for t in previsao]

In [63]:
#Matriz de confusao
confusao = confusion_matrix(y_teste_matrix, y_previsao_matrix)
confusao

array([[16,  0,  0],
       [ 0, 17,  1],
       [ 0,  0, 11]], dtype=int64)